apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: logging
data:
  filebeat.yml: |
    filebeat.inputs:
      - type: filestream
        
        enabled: true
        paths:
          - /apps/logs/**/*.log   # watch your hostPath logs
        scan_frequency: 10s
        multiline:
          pattern: '^[[:space:]]'
          negate: false
          match: after
        parsers:
          - ndjson:
              target: ""
              message_key: message
              ignore_decoding_error: true
          - ndjson:
              target: ""
              message_key: user_id
              ignore_decoding_error: true
          - ndjson:
            target: ""
            message_key: level
            ignore_decoding_error: true
        # processors: # https://www.elastic.co/docs/reference/beats/filebeat/filebeat-input-filestream
        #   - decode_json_fields:
        #       fields: ["message", "user_id"]
        #       process_array: false
        #       max_depth: 1
        #       target: ""
        #       overwrite_keys: false
        #       add_error_key: true

    # Send to Elasticsearch
    output.elasticsearch:
      hosts: ["http://elasticsearch:9200"] # service of your ES
      # username: ""        # set if security enabled
      # password: ""       # set if security enabled

    setup.ilm.enabled: false      # disable ILM if you don’t use it
    setup.template.enabled: true
    setup.ilm.pattern: "{now/d}-000001"
