apiVersion: v1
kind: Pod
metadata:
  name: nfs-nginx
  namespace: default
spec:
  containers:
    - image: nginx
      name: nginx
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: nfs-storage
      securityContext:
        privileged: true
        capabilities:
          add:
          - NET_ADMIN
  volumes:
    - name: nfs-storage
      persistentVolumeClaim:
        claimName: nfs-pvc