kind: PersistentVolume
apiVersion: v1
metadata:
  name: weblog-pv
  namespace: default
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/dntam/Projects/k3d/k8s-dev-lab/chapter-5/tmp/weblog"